name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 8

      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        env:
          TERM: dumb
        with:
          arguments: clean build dist --warning-mode=all
